### ISSUE TITLE
USBNEXT does not load some programs on mounted .dsk

### ISSUE THREAD

**Issue by issalig** [S0urceror/MSX-USB#18]
Test equipment: VG8020 (MSX1)

Mounting a .dsk , for example https://drive.google.com/file/d/1uAYQdP8-Zte_G4u_4CSZ_ULAv0S5TIIP/view?usp=sharing

For example, it loads execrom.com but it does not load bombj.com

Any hint?

**Comment by cristianoag** [comment]
It is running ok on my MSX2. I know you're testing on MSX1 Issalig, I need to get mine from its box to test and that will take some time. Meanwhile, can you test with this ROM https://github.com/cristianoag/MSX-USB/blob/master/drivers/MsxUsbNext/msx/dist/nextor.rom ?

Cristiano

From: issalig ***@***.***>
Sent: Friday, July 1, 2022 9:28 AM
To: S0urceror/MSX-USB ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [S0urceror/MSX-USB] USBNEXT does not load some programs on mounted .dsk (Issue #18)


Test equipment: VG8020 (MSX1)

Mounting a .dsk , for example https://drive.google.com/file/d/1uAYQdP8-Zte_G4u_4CSZ_ULAv0S5TIIP/view?usp=sharing<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1uAYQdP8-Zte_G4u_4CSZ_ULAv0S5TIIP%2Fview%3Fusp%3Dsharing&data=05%7C01%7C%7Cda43164a41ba4741a9be08da5b5d1c84%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922752718412200%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7mtHMqnc%2FSOJVXPMd9XIu%2FMqJQIyorkaIxckUq9byPg%3D&reserved=0>

For example, it loads execrom.com but it does not load bombj.com

Any hint?

-

**Comment by issalig** [comment]
😭 same result. It does not work.
![IMG_20220701_182807](https://user-images.githubusercontent.com/7136948/176934316-e8904059-e5e6-456a-9e01-6e48f76726c7.jpg)

**Comment by issalig** [comment]
Also pay attention to the strange behaviour for the file "BOMBJ.COM"
bombj reads sth but bombj.com reports bad command or file name

Then if I execute "EXECROM.COM" or "EXECROM" it works ok and it exectures that program.
After that if try again with "BOMBJ" it really executes EXECROM. "BOMBJ.COM" also reports bad command as before.

Not sure if I have explained well but it is really weird.

 BOMBJ.COM and EXECROM.COM exist and are reported with dir

**Comment by cristianoag** [comment]
Try only bombj (without the com). You see, there weren’t any read operations. The OS reported the error without even touch the disk.

**Comment by cristianoag** [comment]
How have you created BOMBJ.COM?

**Comment by issalig** [comment]
No, it is a game you can find in this dsk
 https://drive.google.com/file/d/1uAYQdP8-Zte_G4u_4CSZ_ULAv0S5TIIP/view?usp=sharing

**Comment by issalig** [comment]
Under MsxUsbHost it works ok.

**Comment by cristianoag** [comment]
Uhm. Yeah… something is wrong.

I asked how you created bombj.com because originally that game is found as a rom file. Some software transformed the rom file into a com file. I just wanted to know which software to better understand what is going on.

But I found other bugs in the next code that need review as well. Those may be related.

The bug I found is related to how the driver detects if the disk changed. But that information is coming from an assembler routine that I didn’t understand well. Sourceror needs to check as he wrote that part.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by issalig** [comment]
Do not exactly what it does, but pretty sure it was converted and probably uses dirty tricks. But in MsxUsbHost it works nice.

**Comment by cristianoag** [comment]
@issalig, can you please drop me a message on cristianoag@hotmail.com?

**Comment by S0urceror** [comment]
Hi Issalig, I just fixed a bug that Cristiano pointed out earlier. I'll do some further testing and also check that with Bomberjack. I'll let you know the result later.

**Comment by S0urceror** [comment]
On MSX2 it works fine. 

On MSX1 in a debug build it shows this:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/4992808/185799555-f8eadbe2-5ce9-4c10-b3a2-27a477919b13.png">

I noticed on MSX2 it loads much more sectors, like this:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/4992808/185799644-3479930a-95f2-4915-8ba2-45f517c8e1cb.png">

Then resets and starts the game.

**Comment by S0urceror** [comment]
Also tried the old MSXUSB (not Next) and got the same result:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/4992808/185800746-bcbb1a13-0967-41ba-a497-c37d51f0d074.png">

**Comment by S0urceror** [comment]
You are right that the old MSXUSB loads it. Previous test was wrong:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/4992808/185800984-976e53c0-9d7b-485f-ae64-634019fd47f0.png">

Also tried another .ROM file from FileHunter and tried loading with EXECROM. Also doesn't work. Interesting... More research is needed.

**Comment by issalig** [comment]
Next week I will get a sony  hb20p . I will check it there too but I guess it will behave similar to vg8020.

**Comment by S0urceror** [comment]
Hi issalig,

Spend a bit more time research MSXUSBNext:

- MSX1 vs MSX2 does not matter. 
- Memory mapper vs normal 64KB does not matter.
- Having a DOS1 diskrom present in the system => both MSX1 and 2 work.

I tested your VG8020 in OpenMSX. UsbNext with BOMBJ does not work. Once you load a Philips Floppy interface and reset then UsbNext with BOMJ works! Remove it again, reset, and it doesn't work anymore.

So, it looks like a DISKROM must be present to be able to run BOMBJ.com. On MSX2 this is already built-in. On MSX1 this is usually added via a cartridge.

Still, why does the old MSXUSB not have this requirement? The search is not yet over...

**Comment by S0urceror** [comment]
Ok, found it. It looks like this is a very special case in Nextor that causes this. I fixed it and asked it to be included in a next release.

The new release file [nextor.rom](https://github.com/S0urceror/MSX-USB/blob/master/drivers/MsxUsbNext/msx/dist/nextor.rom) in the dist folder is already patched and BOMBJ.COM is working!

**Comment by issalig** [comment]
Congratulations. Really good work.
I have tried it in a HB-20 both from a DSK image and FAT and bombj is working ok.

**Comment by S0urceror** [comment]
Great. Happy to hear it’s working. This was a tough one to find.

Email written on my mobile device
________________________________
