### ISSUE TITLE
The link to the dsks.zip file is invalid

### ISSUE THREAD

**Issue by denjhang** [S0urceror/MSX-USB#5]
https://github.com/S0urceror/MSX-USB/blob/master/INSTALL.md
The files under this link are no longer valid, I actually need these three files.
128mb.DSK 
720kb.DSK
NEXTOR.DSK

**Comment by S0urceror** [comment]
FAT32 support was ceased as explained in the other issue. As a result I don't maintain the .DSK files anymore. Still have them stored somewhere on my machine if you want but you need the old driver to use them.
