### ISSUE TITLE
Cannot use call usbfiles

### ISSUE THREAD

**Issue by denjhang** [S0urceror/MSX-USB#6]
At present, my MSX-USB card can be recognized and run normally, but in the basic interface, all commands with USB are invalid.

**Comment by denjhang** [comment]
![截图未命名0828125901](https://user-images.githubusercontent.com/61811583/131206725-d49e5de0-e6f7-4256-9c32-e37335433783.jpeg)

**Comment by denjhang** [comment]
![ABF64E478EA32F04806471FF24D41CD9](https://user-images.githubusercontent.com/61811583/131206763-d9d6374a-889c-4e8e-a763-46e00e85b309.png)
![49DC25CA311C8A2193560FCC1F48CD28](https://user-images.githubusercontent.com/61811583/131206768-601e5a75-1f09-4c51-ab4b-3574abd216c1.png)

**Comment by denjhang** [comment]
![606F2007DFA08E080C0DE4508094A7E1](https://user-images.githubusercontent.com/61811583/131207144-ff410740-f730-4f23-b879-57c1fa902bd2.png)
This is the result obtained by testing the ROM.

**Comment by denjhang** [comment]
![8AF75366AEAAAE30521D6FD897DC9043](https://user-images.githubusercontent.com/61811583/131207192-fbe49987-9274-4f7b-a992-a786f3c98052.png)
![76BC6EBEE044263B96FF29E55DCBAB2C](https://user-images.githubusercontent.com/61811583/131207200-2fb8598f-f790-4843-8d10-3832cb631d6e.png)


This is the result of using 448k ROM.

**Comment by S0urceror** [comment]
Wow, you made a great looking PCB. 

Unfortunately I stopped supporting FAT32 in the current version of the software. Hardware-wise it still supports it. The main reason was that I wanted to support USB hubs. With an USB hub you can connect multiple USB devices together. Unfortunately you then loose FAT32 support. 

But within Nextor you have all the options to mount dsks, partitions, etc. So if you format your USB stick with FAT16, put Nextor.sys and Command2.com on it, it will boot. The rest is looking good! The ROM mapper works.

P.S. I intend to create a boot-menu where you can select FAT16/FAT32 and an upcoming USB Terminal mode. 
P.S2. I still need to update the documentation to reflect what I wrote above, sorry for putting you on the wrong path.

**Comment by denjhang** [comment]
![C50EA86083ADA29D236BAB85077A9544](https://user-images.githubusercontent.com/61811583/131207622-ae95a1a1-bbea-4f49-946c-4bcdbe5db5fc.png)
![D8C365613C7DE25023EE2121295FE837](https://user-images.githubusercontent.com/61811583/131207626-a3a207bb-e0be-47f6-ba95-1fae00ee0a66.png)
Now I use a 256mb microSD card into the card reader and format it as fat16, and this screen appears. It has been stuck.

**Comment by denjhang** [comment]
My USB flash drives are all 32GB, and I cannot format them as fat16.

**Comment by denjhang** [comment]
I partitioned my USB flash drives , and then formatted one of the small partitions as fat16, and the result was the same as fat32. msx-usb still cannot recognize the files in the USB flash drive.

**Comment by denjhang** [comment]
So currently I hope you can provide software that supports fat32.

**Comment by denjhang** [comment]
I found the old version of msx-usb (ver.81356b2ba45cf27de9d9aa865c109b03bfe1bfec), now it can be used normally, I am very excited.

**Comment by S0urceror** [comment]
As explained I initially supported FAT32 with separate .DSK image files that could be swapped via the CALL commands (usbfiles, insertdisk, etc.)

Unfortunately the CH376s hardware does not allow combine this with supporting other devices at the same time. Like Ethernet, Keyboard together with an USB stick.

As a result I reverted back to native Nextor support which is FAT16. The CALL commands in the current driver are disabled.

However, I intend to create a super-driver that allows to switch between FAT32, multi-device and terminal mode via hotkeys at the start process. This way we can reinstate this feature for people who want this.
