### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by issalig** [S0urceror/MSX-USB#8]
In document https://github.com/S0urceror/MSX-USB/blob/59ba23478fe6e7d2f0d7b382198182bf3e068de1/INSTALL.md
there is a link to the images "Here the link to the disk images" , this link points to https://github.com/S0urceror/MSX-USB/raw/master/drivers/flashdrive/dist/dsks.zip but it does not exist.

However the correct link I assume is https://github.com/S0urceror/MSX-USB/blob/master/drivers/archive.zip

**Comment by S0urceror** [comment]
No need to work with disk images. That is a left-over from when I did FAT-32 volumes with FAT-16 disk images.

Just format your USB stick with FAT16. That is a bit difficult with modern OS-es but with some command-line you can still do it on Windows 10, MacOS and Linux. Then drop Nextor.sys and Command2.com on it and it should boot.

I saw your post on msx.org but I think you problem is that your particular device is not being recognised. Can you check it's usb class and subclass id with lsusb? It should recognise USB storage class bulk-only devices which are the common one's.

**Comment by S0urceror** [comment]
Btw. I want to reintroduce this feature at some point by allowing to choose between fat32, fat16 and multi-device mode or the recently introduced terminal mode. This is coming somewhere later this year.
